"""Initial migration

Revision ID: c9072cffbb74
Revises: 
Create Date: 2019-02-07 11:12:35.813169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9072cffbb74'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('image', sa.String(length=16000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('omgevinf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=True),
    sa.Column('description', sa.String(length=16000), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('link', sa.String(length=180), nullable=True),
    sa.Column('omgevinfId', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['omgevinfId'], ['omgevinf.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('association',
    sa.Column('artists_id', sa.Integer(), nullable=True),
    sa.Column('performance_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artists_id'], ['artist.id'], ),
    sa.ForeignKeyConstraint(['performance_id'], ['performance.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association')
    op.drop_table('performance')
    op.drop_table('omgevinf')
    op.drop_table('artist')
    # ### end Alembic commands ###
